import { FETCH_PLANET_DATA } from "../actions/actionTypes";

export const actions = {
    FETCH_DATA: "FETCH_DATA",
    FETCH_STAR_DATA: "FETCH_STAR_DATA",
    FETCH_PLANET_DATA: "FETCH_STAR_DATA",
    TOGGLE_AUDIO_MUTE: "TOGGLE_AUDIO_MUTE",
    CHANGE_AUDIO_SOURCE: "CHANGE_AUDIO_SOURCE",
    FILTER_SOLAR_SYSTEMS: "FILTER_SOLAR_SYSTEMS",
    SELECT_SOLAR_SYSTEM: "SELECT_SOLAR_SYSTEM"
}