export const actions = {
  GET_LAST_FETCH: "GET_LAST_FETCH",
  FETCH_STARS_BEGIN: "FETCH_STARS_BEGIN",
  FETCH_STARS_SUCCESS: "FETCH_STARS_SUCCESS",
  FETCH_STARS_FAILED: "FETCH_STARS_FAILED",
  FETCH_PLANETS_BEGIN: "FETCH_PLANETS_BEGIN",
  FETCH_PLANETS_SUCCESS: "FETCH_PLANETS_SUCCESS",
  FETCH_PLANETS_FAILED: "FETCH_PLANETS_FAILED",
  TOGGLE_AUDIO_MUTE: "TOGGLE_AUDIO_MUTE",
  CHANGE_AUDIO_SOURCE: "CHANGE_AUDIO_SOURCE",
  FILTER_SOLAR_SYSTEMS: "FILTER_SOLAR_SYSTEMS",
  SELECT_SOLAR_SYSTEM: "SELECT_SOLAR_SYSTEM"
}