export const actions = {
  GET_LAST_DATA_FETCH: "GET_LAST_FETCH",
  FETCH_STARS_BEGIN: "FETCH_STARS_BEGIN",
  FETCH_STARS_SUCCESS: "FETCH_STARS_SUCCESS",
  FETCH_STARS_FAILED: "FETCH_STARS_FAILED",
  FETCH_PLANETS_BEGIN: "FETCH_PLANETS_BEGIN",
  FETCH_PLANETS_SUCCESS: "FETCH_PLANETS_SUCCESS",
  FETCH_PLANETS_FAILED: "FETCH_PLANETS_FAILED",
  TOGGLE_AUDIO_MUTE: "TOGGLE_AUDIO_MUTE",
  CHANGE_AUDIO_SOURCE: "CHANGE_AUDIO_SOURCE",
  CHANGE_SELECTED_SYSTEM: "CHANGE_SELECTED_SYSTEM",
  CHANGE_FILTERS: "CHANGE_FILTERS",
  FILTER_STARS_MASS: "FILTER_STARS_MASS",
  FILTER_STARS_RADIUS: "FILTER_SOLAR_RADIUS",
  FILTER_STARS_TEMP: "FILTER_SOLAR_TEMP",
  SELECT_SOLAR_SYSTEM: "SELECT_SOLAR_SYSTEM"
}