export const STARS_ASYNC_GET_BEGIN = 'STARS_ASYNC_GET_BEGIN';
export const STARS_ASYNC_GET_SUCCESS = 'STARS_ASYNC_GET_SUCCESS';
export const STARS_ASYNC_GET_FAILED = 'STARS_ASYNC_GET_FAILED';

export const PLANETS_ASYNC_GET_BEGIN = 'PLANETS_ASYNC_GET_BEGIN';
export const PLANETS_ASYNC_GET_SUCCESS = 'PLANETS_ASYNC_GET_SUCCESS';
export const PLANETS_ASYNC_GET_FAILED = 'PLANETS_ASYNC_GET_FAILED';
