export const TOGGLE_AUDIO_MUTE = 'TOGGLE_AUDIO_MUTE';
export const CHANGE_AUDIO_SOURCE = 'CHANGE_AUDIO_SOURCE';

export const GET_SELECTED_SOLARSYSTEM = 'GET_SELECTED_SOLARSYSTEM';
export const SET_SELECTED_SOLARSYSTEM = 'SET_SELECTED_SOLARSYSTEM';

export const CREATE_BOOKMARK = 'CREATE_BOOKMARK';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
export const DELETE_ALL_BOOKMARKS = 'DELETE_ALL_BOOKMARKS';

export const BOOKMARKS_TOGGLE_SOLARSYSTEM = 'BOOKMARKS_ADD_SOLARSYSTEM';

export const GET_LAST_DATA_FETCH_DATETIME = 'GET_LAST_DATA_FETCH_DATETIME';
export const SET_LAST_DATA_FETCH_DATETIME = 'SET_LAST_DATA_FETCH_DATETIME';
