export const GET_LAST_DATA_FETCH = "GET_LAST_FETCH";
export const SET_LAST_DATA_FETCH = "SET_LAST_DATA_FETCH";

export const ASYNC_GET_STARS_BEGIN = "ASYNC_GET_STARS_BEGIN";
export const ASYNC_GET_STARS_SUCCESS = "ASYNC_GET_STARS_SUCCESS";
export const ASYNC_GET_STARS_FAILED = "ASYNC_GET_STARS_FAILED";
export const ASYNC_GET_PLANETS_BEGIN = "ASYNC_GET_PLANETS_BEGIN";
export const ASYNC_GET_PLANETS_SUCCESS = "ASYNC_GET_PLANETS_SUCCESS";
export const ASYNC_GET_PLANETS_FAILED = "ASYNC_GET_PLANETS_FAILED";
