import {
    GET_LAST_DATA_FETCH,
    SET_LAST_DATA_FETCH,
    ASYNC_GET_STARS_BEGIN,
    ASYNC_GET_STARS_SUCCESS,
    ASYNC_GET_STARS_FAILED,
    ASYNC_GET_PLANETS_BEGIN,
    ASYNC_GET_PLANETS_SUCCESS,
    ASYNC_GET_PLANETS_FAILED,
  } from './data';
  
  import {
    TOGGLE_AUDIO_MUTE,
    CHANGE_AUDIO_SOURCE
  } from './ui';
  
  export const actions = {
    data: {
      ASYNC_GET_STARS_BEGIN,
      ASYNC_GET_STARS_SUCCESS,
      ASYNC_GET_STARS_FAILED,
      ASYNC_GET_PLANETS_BEGIN,
      ASYNC_GET_PLANETS_SUCCESS,
      ASYNC_GET_PLANETS_FAILED,
    },
    ui: {
      GET_LAST_DATA_FETCH,
      SET_LAST_DATA_FETCH,
      TOGGLE_AUDIO_MUTE,
      CHANGE_AUDIO_SOURCE,
      SELECT_SOLAR_SYSTEM: "SELECT_SOLAR_SYSTEM",
      CHANGE_SELECTED_SYSTEM:"CHANGE_SELECTED_SYSTEM",  
    },
    filters: {
      CHANGE_FILTERS: "CHANGE_FILTERS",
      FILTER_STARS_MASS: "FILTER_STARS_MASS",
      FILTER_STARS_RADIUS: "FILTER_SOLAR_RADIUS",
      FILTER_STARS_TEMP: "FILTER_SOLAR_TEMP",  
    },
    sorting: {
  
    },
  };
  