export const AUDIO_MUTE_TOGGLE = 'AUDIO_MUTE_TOGGLE';
export const AUDIO_SOURCE_CHANGE = 'AUDIO_SOURCE_CHANGE';

export const SELECTED_SOLARSYSTEM_GET = 'SELECTED_SOLARSYSTEM_GET';
export const SELECTED_SOLARSYSTEM_SET = 'SELECTED_SOLARSYSTEM_SET';

export const BOOKMARKS_ADD = 'BOOKMARKS_ADD';
export const BOOKMARKS_DELETE = 'BOOKMARKS_DELETE';
export const BOOKMARKS_DELETE_ALL = 'BOOKMARKS_DELETE_ALL';
export const BOOKMARKS_TOGGLE_SOLARSYSTEM = 'BOOKMARKS_ADD_SOLARSYSTEM';

export const LAST_DATA_FETCH_DATETIME_GET = 'LAST_DATA_FETCH_DATETIME_GET';
export const LAST_DATA_FETCH_DATETIME_SET = 'LAST_DATA_FETCH_DATETIME_SET';
