export const TOGGLE_AUDIO_MUTE = 'TOGGLE_AUDIO_MUTE';
export const CHANGE_AUDIO_SOURCE = 'CHANGE_AUDIO_SOURCE';

export const GET_SELECTED_SOLARSYSTEM = 'GET_SELECTED_SOLARSYSTEM';
export const SET_SELECTED_SOLARSYSTEM = 'SET_SELECTED_SOLARSYSTEM';

export const BOOKMARKS_ADD = 'BOOKMARKS_ADD';
export const BOOKMARKS_DELETE = 'BOOKMARKS_DELETE';
export const BOOKMARKS_DELETE_ALL = 'BOOKMARKS_DELETE_ALL';
export const BOOKMARKS_TOGGLE_SOLARSYSTEM = 'BOOKMARKS_ADD_SOLARSYSTEM';

export const GET_LAST_DATA_FETCH_DATETIME = 'GET_LAST_DATA_FETCH_DATETIME';
export const SET_LAST_DATA_FETCH_DATETIME = 'SET_LAST_DATA_FETCH_DATETIME';
