export const LAST_DATA_FETCH_DATETIME_GET = 'LAST_DATA_FETCH_DATETIME_GET';
export const LAST_DATA_FETCH_DATETIME_SET = 'LAST_DATA_FETCH_DATETIME_SET';

export const AUDIO_MUTE_TOGGLE = 'AUDIO_MUTE_TOGGLE';
export const AUDIO_SOURCE_CHANGE = 'AUDIO_SOURCE_CHANGE';

export const SELECTED_SOLARSYSTEM_GET = 'SELECTED_SOLARSYSTEM_GET';
export const SELECTED_SOLARSYSTEM_SET = 'SELECTED_SOLARSYSTEM_SET';
